<a href="https://colab.research.google.com/github/jeeet0700/Python_Advance/blob/main/Numpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([1,0,4,9,2,7])
a

array([1, 0, 4, 9, 2, 7])

In [3]:
np.sort(a)

array([0, 1, 2, 4, 7, 9])

In [4]:
np.argsort(a)

array([1, 0, 4, 2, 5, 3])

In [3]:
a=np.array([[22,0,6],[54,63,2],[5,2,9]])
a

array([[22,  0,  6],
       [54, 63,  2],
       [ 5,  2,  9]])

In [4]:
np.sort(a)

array([[ 0,  6, 22],
       [ 2, 54, 63],
       [ 2,  5,  9]])

In [5]:
np.sort(a,axis=1)

array([[ 0,  6, 22],
       [ 2, 54, 63],
       [ 2,  5,  9]])

In [6]:
np.sort(a,axis=0)

array([[ 5,  0,  2],
       [22,  2,  6],
       [54, 63,  9]])

In [7]:
np.argsort(a)

array([[1, 2, 0],
       [2, 0, 1],
       [1, 0, 2]])

In [8]:
a

array([[22,  0,  6],
       [54, 63,  2],
       [ 5,  2,  9]])

In [10]:
np.argsort(a,axis=0)

array([[2, 0, 1],
       [0, 2, 0],
       [1, 1, 2]])

In [1]:
import numpy as np

In [3]:
a=np.arange(0,24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
a.shape

(6, 4)

In [5]:
a.size

24

In [6]:
a.ndim

2

In [7]:
a.dtype

dtype('int64')

In [8]:
a,b,c=[1,2,3]
a

1

In [9]:
b

2

In [10]:
c

3

In [11]:
data=np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [12]:
data.shape

(3, 1)

In [13]:
data

array([[1],
       [2],
       [3]])

In [14]:
data.T

array([[1, 2, 3]])

In [15]:
data=np.array([1,2,3])
a,b,c=data.T

In [16]:
a

1

In [17]:
a,b,c=data

In [18]:
a

1

In [19]:
data=np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [20]:
data.T

array([[1, 2, 3]])

In [21]:
a,b,c=data

In [22]:
a

array([1])

In [23]:
a,b,c=data.T

ValueError: ignored

In [1]:
import numpy as np

In [2]:
# np.dot
# np.matmul
# @

In [4]:
a=np.arange(2,11).reshape(3,3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [5]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.matmul(a,b)

array([[ 42,  51,  60],
       [ 78,  96, 114],
       [114, 141, 168]])

In [7]:
np.matmul(b,a)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [8]:
a@b

array([[ 42,  51,  60],
       [ 78,  96, 114],
       [114, 141, 168]])

In [9]:
b@a

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [10]:
np.dot(a,b)

array([[ 42,  51,  60],
       [ 78,  96, 114],
       [114, 141, 168]])

In [11]:
np.dot(b,a)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [12]:
np.dot(2,4)

8

In [13]:
np.matmul(2,4)

ValueError: ignored

In [15]:
d=np.arange(1,5)
e=np.arange(6,10)
print(d)
print(e)

[1 2 3 4]
[6 7 8 9]


In [16]:
np.dot(d,e)

80

In [17]:
np.matmul(d,e)

80