<a href="https://colab.research.google.com/github/jeeet0700/Python_Advance/blob/main/Numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
a[3]

4

In [5]:
a[-9]

4

In [7]:
a[0:9:2]

array([1, 3, 5, 7, 9])

In [8]:
a[[1,4,7]]

array([2, 5, 8])

In [9]:
a[(1,4,7)]

IndexError: ignored

In [11]:
b=a.reshape(3,4)

In [12]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
b[:2,:2]

array([[1, 2],
       [5, 6]])

In [18]:
b[:,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [19]:
b[::2,::2]

array([[ 1,  3],
       [ 9, 11]])

In [20]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
b[[0,0,1,2],[0,2,3,1]]

array([ 1,  3,  8, 10])

In [22]:
b[0,1]

2

In [23]:
b[[0,1],:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
b[[0,1],::2]

array([[1, 3],
       [5, 7]])

In [26]:
c=np.arange(1,25).reshape(4,6)
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [29]:
c[:,[1,2,4]]

array([[ 2,  3,  5],
       [ 8,  9, 11],
       [14, 15, 17],
       [20, 21, 23]])

In [30]:
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [31]:
c[:,::-1]

array([[ 6,  5,  4,  3,  2,  1],
       [12, 11, 10,  9,  8,  7],
       [18, 17, 16, 15, 14, 13],
       [24, 23, 22, 21, 20, 19]])

In [32]:
c[::-1,:]

array([[19, 20, 21, 22, 23, 24],
       [13, 14, 15, 16, 17, 18],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6]])

In [33]:
c[::-2,::-2]

array([[24, 22, 20],
       [12, 10,  8]])